// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrNtKLOunu87fHldcVNovcOcwOq-gTOHU',
    appId: '1:539238753612:web:05e690c73d87d407a89be9',
    messagingSenderId: '539238753612',
    projectId: 'propertieexplore',
    authDomain: 'propertieexplore.firebaseapp.com',
    storageBucket: 'propertieexplore.firebasestorage.app',
    measurementId: 'G-3TH6YQ893W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwLFqx24WjC9yGa1KlWoRH1DCrLlbnBXQ',
    appId: '1:539238753612:android:86b0548f50120211a89be9',
    messagingSenderId: '539238753612',
    projectId: 'propertieexplore',
    storageBucket: 'propertieexplore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDolIbPVJFLpiqX6RHnJMGX3N8oVLmQJio',
    appId: '1:539238753612:ios:61b20d86c686b93aa89be9',
    messagingSenderId: '539238753612',
    projectId: 'propertieexplore',
    storageBucket: 'propertieexplore.firebasestorage.app',
    iosBundleId: 'com.example.propertieExplore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDolIbPVJFLpiqX6RHnJMGX3N8oVLmQJio',
    appId: '1:539238753612:ios:61b20d86c686b93aa89be9',
    messagingSenderId: '539238753612',
    projectId: 'propertieexplore',
    storageBucket: 'propertieexplore.firebasestorage.app',
    iosBundleId: 'com.example.propertieExplore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrNtKLOunu87fHldcVNovcOcwOq-gTOHU',
    appId: '1:539238753612:web:cb8b86a32ea5056da89be9',
    messagingSenderId: '539238753612',
    projectId: 'propertieexplore',
    authDomain: 'propertieexplore.firebaseapp.com',
    storageBucket: 'propertieexplore.firebasestorage.app',
    measurementId: 'G-4R2K1CMHX1',
  );
}
